host: user-api-thoth-test-core.apps.zero.massopen.cloud
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: rhel:8
    operating_system:
      name: rhel
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: thoth-advise
    configuration:
      labels: [bot, kebechet]
