host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: rhel:8
    operating_system:
      name: rhel
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: advise
    configuration:
      labels: [bot, kebechet]
  - name: version
    configuration:
      labels: [bot, kebechet]
      changelog_file: true
