host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv

runtime_environments:
  - name: fedora:34
    operating_system:
      name: fedora
      version: "34"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: update
    configuration:
      labels: [bot]
  - name: thoth-advise
    configuration:
      labels: [bot, kebechet]
  - name: version
    configuration:
      maintainers:
        - KPostOffice
      labels: [bot]
      changelog_file: true
